package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_03;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/03/higher-order-promises/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Promise"},{module=>"Mojo::Promise::Role::HigherOrder"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 03)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 03)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/03/higher-order-promises/> (retrieved on 2018-12-30). Visit the URL for the full contents.

