package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_10;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/10/minion-stands-alone/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Beam::Minion"},{module=>"Minion"},{module=>"Minion::Backend::SQLite"},{module=>"Minion::Command::minion::job"},{module=>"Minion::Command::minion::worker"},{module=>"Time::HiRes"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 10)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/10/minion-stands-alone/> (retrieved on 2018-12-30). Visit the URL for the full contents.

