package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_24;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/24/async-await-the-mojo-way/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Coro"},{module=>"Mojo::AsyncAwait"},{module=>"Mojo::Promise"},{module=>"Mojolicious::Plugin::PromiseActions"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 24)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/24/async-await-the-mojo-way/> (retrieved on 2018-12-30). Visit the URL for the full contents.

