package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_06;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/06/making-a-list-with-yancy/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::SQLite"},{module=>"Mojo::SQLite::Migrations"},{module=>"Mojolicious::Plugin::TagHelpers"},{module=>"Yancy"},{module=>"Yancy::Controller::Yancy"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 06)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 06)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/06/making-a-list-with-yancy/> (retrieved on 2018-12-30). Visit the URL for the full contents.

