package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_11;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/11/who-watches-the-minions/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Minion"},{module=>"Minion::Command::minion::job"},{module=>"Mojolicious::Command::daemon"},{module=>"Mojolicious::Plugin::Minion::Admin"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 11)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/11/who-watches-the-minions/> (retrieved on 2018-12-30). Visit the URL for the full contents.

