package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_16;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/16/browser-diet/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Headers"},{module=>"Mojolicious::Plugin::StaticCache"},{module=>"Mojolicious::Plugin::TagHelpers"},{module=>"Plack"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 16)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/16/browser-diet/> (retrieved on 2018-12-30). Visit the URL for the full contents.

