package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_18;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/18/a-view-to-a-pod/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojolicious::Plugin::PODRenderer"},{module=>"Mojolicious::Plugin::PODViewer"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 18)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/18/a-view-to-a-pod/> (retrieved on 2018-12-30). Visit the URL for the full contents.

