package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_12;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/12/dancer-and-minion/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer"},{module=>"Dancer2"},{module=>"Minion"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 12)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 12)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/12/dancer-and-minion/> (retrieved on 2018-12-30). Visit the URL for the full contents.

