package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_22;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/22/use-carton-for-your-mojolicious-app-deployment/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Carton"},{module=>"Mojo::Pg"},{module=>"Mojo::Server::Hypnotoad"},{module=>"Mojolicious::Plugin::DefaultHelpers"},{module=>"lib"},{module=>"lib::relative"},{module=>"local::lib"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 22)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 22)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/22/use-carton-for-your-mojolicious-app-deployment/> (retrieved on 2018-12-30). Visit the URL for the full contents.

