package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_02;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/02/automatic-reload-for-rapid-development/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojolicious::Plugin::AutoReload"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 02)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 02)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/02/automatic-reload-for-rapid-development/> (retrieved on 2018-12-30). Visit the URL for the full contents.

