package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_15;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/15/practical-web-content-munging/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"HTML::WikiConverter"},{module=>"Mojo::Collection"},{module=>"Mojo::DOM"},{module=>"Mojo::File"},{module=>"Mojo::Message::Response"},{module=>"Mojo::Transaction::HTTP"},{module=>"Mojo::UserAgent"},{module=>"String::Truncate"},{module=>"Time::Piece"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 15)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/15/practical-web-content-munging/> (retrieved on 2018-12-30). Visit the URL for the full contents.

