package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_08;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/08/authenticating-with-ldap/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Crypt::Eksblowfish::Bcrypt"},{module=>"DBI"},{module=>"MojoX::Auth::Simple"},{module=>"MojoX::Session"},{module=>"Mojolicious::Controller"},{module=>"Mojolicious::Plugin::Authentication"},{module=>"Mojolicious::Plugin::Config"},{module=>"Mojolicious::Plugin::Scrypt"},{module=>"Net::LDAP"},{module=>"Passwords"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 08)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 08)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/08/authenticating-with-ldap/> (retrieved on 2018-12-30). Visit the URL for the full contents.

