package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_21;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/21/a-little-christmas-template-cooking/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"File::Find"},{module=>"Mojo::File"},{module=>"Mojo::Template"},{module=>"Time::Piece"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 21)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/21/a-little-christmas-template-cooking/> (retrieved on 2018-12-30). Visit the URL for the full contents.

