package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_20;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/20/testing-dancer/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::WebSocket"},{module=>"Dancer2::Template::Simple"},{module=>"Mojo::DOM::CSS"},{module=>"Mojo::JSON::Pointer"},{module=>"Mojo::Server::PSGI"},{module=>"Mojo::UserAgent"},{module=>"Mojolicious::Plugin::Mount"},{module=>"Mojolicious::Plugin::MountPSGI"},{module=>"PSGI"},{module=>"Plack::Test"},{module=>"Test::Mojo"},{module=>"Test::Mojo::Role::PSGI"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 20)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/20/testing-dancer/> (retrieved on 2018-12-30). Visit the URL for the full contents.

