package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_04;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/04/testing-hooks-and-helpers/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::HelloWorld"},{module=>"Mojo::Message::Request"},{module=>"Mojo::Message::Response"},{module=>"Mojolicious"},{module=>"Test::Mojo"},{module=>"Test::Mojo::Role::PSGI"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 04)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 04)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/04/testing-hooks-and-helpers/> (retrieved on 2018-12-30). Visit the URL for the full contents.

