package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_14;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/14/a-practical-example-of-mojo-dom/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojo::Base"},{module=>"Mojo::DOM"},{module=>"Mojo::File"},{module=>"Mojo::Util"},{module=>"Mojolicious::Plugin::Config"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 14)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 14)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/14/a-practical-example-of-mojo-dom/> (retrieved on 2018-12-30). Visit the URL for the full contents.

