package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_23;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/23/mojolicious-and-angular/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Minion"},{module=>"Mojo::DOM"},{module=>"Mojo::Server::Hypnotoad"},{module=>"Mojolicious::Command::generate::app"},{module=>"Mojolicious::Commands"},{module=>"Mojolicious::Plugin::AssetPack"},{module=>"Mojolicious::Plugin::OAuth2"},{module=>"Mojolicious::Plugin::OpenAPI"},{module=>"Test::Mojo"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 23)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/23/mojolicious-and-angular/> (retrieved on 2018-12-30). Visit the URL for the full contents.

