package Acme::CPANModules::Import::MojoliciousAdvent::2018_12_09;

# DATE
# VERSION

our $LIST = {description=>"This list is generated by extracting module names mentioned in [https://mojolicious.io/blog/2018/12/09/add-a-theme-system-to-your-mojolicious-app/] (retrieved on 2018-12-30). Visit the URL for the full contents.",entries=>[{module=>"Mojolicious::Plugin::Config"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2018 (day 09)"};

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2018 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://mojolicious.io/blog/2018/12/09/add-a-theme-system-to-your-mojolicious-app/> (retrieved on 2018-12-30). Visit the URL for the full contents.

